version: '2'

services:
  mongo:
    image: mongo:latest

  web:
    build: .
    image: activist-app
    env_file: web-variables.env
    links:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
